/*  --------------------
 *  lp\zh-Hans + lp\zh-Hant - Alibaba
 *  (c) Kingcean Tuan, 2014.
 *
 *  File  zh.ts
 *  Description  Language pack for Chinese.
 *  Owner  Kingcean Tuan <kingcean@live.com>
 *  --------------------  */

/// <reference path="resources.ts" />

namespace AliHub.Res {

    /**
      * Language pack for zh-Hans.
      */
    export class Lp_zhHans implements LanguagePackContract {

        public lang = "zh-Hans";

        public strings = {
            homepage: "主页",
            appCenter: "应用中心",
            page: "页面",
            pages: "页面",
            first: "第一",
            last: "最后",
            previous: "前面",
            next: "后面",
            total: "总数",
            current: "当前",
            index: "索引",
            bindingError: "无法绑定",
            refresh: "刷新",
            reload: "重载",
            member: "会员",
            myMembers: "我的会员",
            recentDays: "近{0}天",
            planned: "未处理",
            processing: "处理中",
            completed: "已完成",
            ladyName: "{0}女士",
            gentlemanName: "{0}先生",
            reminder: "提醒",
            note: "便签",
            totalScore: "综合评分",
            cents: "{0}分",
            level: "等级",
            collapse: "收起",
            expand: "展开",
            showAll: "显示全部",
            followUp: "跟进",
            noFollowUp: "暂未跟进",
            memberTags: "会员印象",
            types: "类别",
            history: "历史",
            trend: "趋势",
            distribution: "分布",
            newTasks: "{0}条新任务",
            bizTasks: "工作任务",
            summaryReports: "统计报表",
            jobMgm: "工作管理",
            createTask: "新建任务",
            seeMore: "查看更多",
            exit: "退出",
            register: "注册",
            login: "登录",
            logout: "注销",
            search: "搜索",
            filter: "过滤",
            typeKeywords: "输入搜索关键词",
            requestHelp: "{0} 正在请求帮助中",
            cannotFind: "该{0}并不存在",
            newItem: "新建",
            createItem: "创建",
            addItem: "添加",
            getItem: "获取",
            setItem: "设置",
            modifyItem: "修改",
            updateItem: "更新",
            replaceItem: "替换",
            overrideItem: "覆盖",
            fillItem: "填充",
            removeItem: "移除",
            deleteItem: "删除",
            clearItem: "清空",
            cleanUp: "清理",
            ok: "确定",
            save: "保存",
            cancel: "取消",
            turnBack: "返回",
            rollback: "回滚",
            undo: "撤销",
            redo: "重复",
            cut: "剪切",
            copy: "复制",
            copySomething: "复制{0}",
            paste: "粘贴",
            clipboard: "剪切板",
            navigateTo: "导航至",
            settings: "设置",
            options: "选项",
            profile: "档案",
            draft: "草稿",
            open: "打开",
            close: "关闭",
            turnOn: "开启",
            turnOff: "关闭",
            layout: "布局",
            add: "添加",
            insert: "插入",
            edit: "编辑",
            remove: "移除",
            delete: "删除",
            clear: "清空",
            title: "标题",
            content: "内容",
            text: "文本",
            richtext: "富文本",
            properties: "属性",
            wizard: "向导",
            slide: "幻灯片",
            photo: "照片",
            image: "图片",
            images: "图片",
            audio: "音频",
            video: "视频",
            movie: "电影",
            movies: "电影",
            document: "文档",
            documents: "文档",
            link: "链接",
            links: "链接",
            hyperlink: "超链接",
            website: "网站",
            sns: "社交网络",
            favorate: "收藏",
            game: "游戏",
            games: "游戏",
            file: "文件",
            files: "文件",
            folder: "文件夹",
            dir: "目录",
            moveUp: "上移",
            moveRight: "右移",
            moveDown: "下移",
            moveLeft: "左移",
            module: "模块",
            component: "组件",
            chapter: "章",
            section: "节",
            update: "更新",
            upload: "上传",
            download: "下载",
            switch: "切换",
            switchCamera: "切换摄像头",
            capturePhoto: "拍照",
            record: "录制",
            assign: "委派",
            reassign: "转交",
            flag: "标记",
            send: "发送",
            reply: "回复",
            replyAll: "全部回复",
            forward: "转发",
            cc: "抄送",
            bcc: "秘密抄送",
            phoneCall: "拨打",
            contact: "联系",
            contactMember: "联系会员",
            attach: "附加",
            attachment: "附件",
            expired: "已超时",
            message: "消息",
            notification: "通知",
            feedback: "反馈",
            help: "帮助",
            support: "支持",
            window: "窗口",
            aries: "白羊座",
            taurus: "金牛座",
            gemini: "双子座",
            cancer: "巨蟹座",
            leo: "狮子座",
            virgo: "室女座",
            libra: "天秤座",
            scorpio: "天蝎座",
            sagittarius: "射手座",
            capricorn: "摩羯座",
            aquarius: "水瓶座",
            pisces: "双鱼座",
            ophiuchus: "蛇夫座",
            horoscope: "星座",
            astrology: "占星",
            loading: "加载中",
            failToLoadData: "数据加载失败",
            surname: "姓氏",
            givenname: "名字",
            middleName: "中间名",
            nickname: "昵称",
            city: "城市",
            street: "接到",
            country: "国家",
            birthday: "生日",
            age: "年龄",
            gender: "性别",
            male: "男",
            female: "女",
            other: "其它",
            fromSource: "从",
            toTarget: "至",
            millisecondsNum: "{0}微秒",
            secondsNum: "{0}秒",
            minutesNum: "{0}分",
            hoursNum: "{0}小时",
            daysNum: "{0}天",
            weeksNum: "{0}周",
            timeLocaleSep: "",
            today: "今天",
            tomorrowTime: "明天 {0}",
            tomorrow: "明天",
            secondsAgo: "数秒之前",
            minuteAgo: "一分钟前",
            minutesTwoAgo: "两分钟前",
            minutesAgo: "{0}分钟前",
            hourAgo: "一个小时前",
            hoursTwoAgo: "两个小时前",
            hoursAgo: "{0}个小时前",
            yesterdayTime: "昨天 {0}",
            yesterday: "昨天",
            daysTwoAgo: "前天",
            daysAgo: "{0}天前",
            lastWeekDay: "上{0}",
            lastWeek: "上周",
            future: "未来",
            date: "日期",
            day: "天",
            week: "星期",
            weekday: "工作日",
            weekend: "周末",
            week0c: "日",
            week1c: "一",
            week2c: "二",
            week3c: "三",
            week4c: "四",
            week5c: "五",
            week6c: "六",
            week0s: "周日",
            week1s: "周一",
            week2s: "周二",
            week3s: "周三",
            week4s: "周四",
            week5s: "周五",
            week6s: "周六",
            week0f: "星期天",
            week1f: "星期一",
            week2f: "星期二",
            week3f: "星期三",
            week4f: "星期四",
            week5f: "星期五",
            week6f: "星期六",
            week0t: "周日 {0}",
            week1t: "周一 {0}",
            week2t: "周二 {0}",
            week3t: "周三 {0}",
            week4t: "周四 {0}",
            week5t: "周五 {0}",
            week6t: "周六 {0}",
            month: "月",
            month0s: "1月",
            month1s: "2月",
            month2s: "3月",
            month3s: "4月",
            month4s: "5月",
            month5s: "6月",
            month6s: "7月",
            month7s: "8月",
            month8s: "9月",
            month9s: "10月",
            monthAs: "11月",
            monthBs: "12月",
            month0f: "一月",
            month1f: "二月",
            month2f: "三月",
            month3f: "四月",
            month4f: "五月",
            month5f: "六月",
            month6f: "七月",
            month7f: "八月",
            month8f: "九月",
            month9f: "十月",
            monthAf: "十一月",
            monthBf: "十二月",
            year: "年",
            am: "上午",
            pm: "下午",
            empty: "暂无",
            commaSymbol: "，",
            colonSymbol: "：",
            ellipsisSymbol: "……",
            semicolonSymbol: "；",
            enumCommaSymbol: "、",
            periodSymbol: "。"
        };

        public template(templ: AliHub.Res.Templates): AliHub.Res.Templates {
            if (!templ) return null;
            templ.strings.reg(this.lang, this.strings);
            templ.strings.reg("zh-CN", this.strings);
            templ.strings.reg("zh-SG", this.strings);
            return templ;
        }
    }

    /**
      * Language pack for zh-Hant.
      */
    export class Lp_zhHant implements LanguagePackContract {

        public lang = "zh-Hant";

        public strings = {
            homepage: "主頁",
            appCenter: "應用中心",
            page: "頁面",
            pages: "頁面",
            first: "第一",
            last: "最後",
            previous: "前面",
            next: "後面",
            total: "總數",
            current: "當前",
            index: "索引",
            bindingError: "無法綁定",
            refresh: "刷新",
            reload: "重載",
            member: "會員",
            myMembers: "我的會員",
            recentDays: "近{0}天",
            planned: "未處理",
            processing: "處理中",
            completed: "已完成",
            ladyName: "{0}女士",
            gentlemanName: "{0}先生",
            reminder: "提醒",
            note: "便簽",
            totalScore: "綜合評分",
            cents: "{0}分",
            level: "等級",
            collapse: "收起",
            expand: "展開",
            showAll: "顯示全部",
            followUp: "跟進",
            noFollowUp: "暫未跟進",
            memberTags: "會員印象",
            types: "類別",
            history: "歷史",
            trend: "趨勢",
            distribution: "分佈",
            newTasks: "{0}條新任務",
            bizTasks: "工作任務",
            summaryReports: "統計報表",
            jobMgm: "工作管理",
            createTask: "新建任務",
            seeMore: "查看更多",
            exit: "退出",
            register: "註冊",
            login: "登錄",
            logout: "登出",
            search: "搜索",
            filter: "過濾",
            typeKeywords: "輸入搜索關鍵字",
            requestHelp: "{0} 正在請求説明中",
            cannotFind: "該{0}並不存在",
            newItem: "新建",
            createItem: "創建",
            addItem: "添加",
            getItem: "獲取",
            setItem: "設置",
            modifyItem: "修改",
            updateItem: "更新",
            replaceItem: "替換",
            overrideItem: "覆蓋",
            fillItem: "填充",
            removeItem: "移除",
            deleteItem: "刪除",
            clearItem: "清空",
            cleanUp: "清理",
            ok: "確定",
            save: "保存",
            cancel: "取消",
            turnBack: "返回",
            rollback: "回滾",
            undo: "撤銷",
            redo: "重複",
            cut: "剪切",
            copy: "複製",
            copySomething: "複製{0}",
            paste: "粘貼",
            clipboard: "剪切板",
            navigateTo: "導航至",
            settings: "設置",
            options: "選項",
            profile: "檔案",
            draft: "草稿",
            open: "打開",
            close: "關閉",
            turnOn: "開啟",
            turnOff: "關閉",
            layout: "佈局",
            add: "添加",
            insert: "插入",
            edit: "編輯",
            remove: "移除",
            delete: "刪除",
            clear: "清空",
            title: "標題",
            content: "內容",
            text: "文本",
            richtext: "富文本",
            properties: "屬性",
            wizard: "嚮導",
            slide: "幻燈片",
            photo: "照片",
            image: "圖片",
            images: "圖片",
            audio: "音訊",
            video: "視頻",
            movie: "電影",
            movies: "電影",
            document: "文檔",
            documents: "文檔",
            link: "連結",
            links: "連結",
            hyperlink: "超連結",
            website: "網站",
            sns: "社交網路",
            favorate: "收藏",
            game: "遊戲",
            games: "遊戲",
            file: "檔",
            files: "檔",
            folder: "資料夾",
            dir: "目錄",
            moveUp: "上移",
            moveRight: "右移",
            moveDown: "下移",
            moveLeft: "左移",
            module: "模組",
            component: "元件",
            chapter: "章",
            section: "節",
            update: "更新",
            upload: "上傳",
            download: "下載",
            switch: "切換",
            switchCamera: "切換攝像頭",
            capturePhoto: "拍照",
            record: "錄製",
            assign: "委派",
            reassign: "轉交",
            flag: "標記",
            send: "發送",
            reply: "回復",
            replyAll: "全部回復",
            forward: "轉發",
            cc: "抄送",
            bcc: "秘密抄送",
            phoneCall: "撥打",
            contact: "聯繫",
            contactMember: "聯繫會員",
            attach: "附加",
            attachment: "附件",
            expired: "已超時",
            message: "消息",
            notification: "通知",
            feedback: "回饋",
            help: "説明",
            support: "支援",
            window: "視窗",
            aries: "白羊座",
            taurus: "金牛座",
            gemini: "雙子座",
            cancer: "巨蟹座",
            leo: "獅子座",
            virgo: "室女座",
            libra: "天秤座",
            scorpio: "天蠍座",
            sagittarius: "射手座",
            capricorn: "摩羯座",
            aquarius: "水瓶座",
            pisces: "雙魚座",
            ophiuchus: "蛇夫座",
            horoscope: "星座",
            astrology: "占星",
            loading: "載入中",
            failToLoadData: "資料載入失敗",
            surname: "姓氏",
            givenname: "名字",
            middleName: "中間名",
            nickname: "昵稱",
            city: "城市",
            street: "接到",
            country: "國家",
            birthday: "生日",
            age: "年齡",
            gender: "性別",
            male: "男",
            female: "女",
            other: "其它",
            fromSource: "從",
            toTarget: "至",
            millisecondsNum: "{0}微秒",
            secondsNum: "{0}秒",
            minutesNum: "{0}分",
            hoursNum: "{0}小時",
            daysNum: "{0}天",
            weeksNum: "{0}周",
            timeLocaleSep: "",
            today: "今天",
            tomorrowTime: "明天 {0}",
            tomorrow: "明天",
            secondsAgo: "數秒之前",
            minuteAgo: "一分鐘前",
            minutesTwoAgo: "兩分鐘前",
            minutesAgo: "{0}分鐘前",
            hourAgo: "一個小時前",
            hoursTwoAgo: "兩個小時前",
            hoursAgo: "{0}個小時前",
            yesterdayTime: "昨天 {0}",
            yesterday: "昨天",
            daysTwoAgo: "前天",
            daysAgo: "{0}天前",
            lastWeekDay: "上{0}",
            lastWeek: "上周",
            future: "未來",
            date: "日期",
            day: "天",
            week: "星期",
            weekday: "工作日",
            weekend: "週末",
            week0c: "日",
            week1c: "一",
            week2c: "二",
            week3c: "三",
            week4c: "四",
            week5c: "五",
            week6c: "六",
            week0s: "周日",
            week1s: "週一",
            week2s: "週二",
            week3s: "週三",
            week4s: "週四",
            week5s: "週五",
            week6s: "週六",
            week0f: "星期天",
            week1f: "星期一",
            week2f: "星期二",
            week3f: "星期三",
            week4f: "星期四",
            week5f: "星期五",
            week6f: "星期六",
            week0t: "周日 {0}",
            week1t: "週一 {0}",
            week2t: "週二 {0}",
            week3t: "週三 {0}",
            week4t: "週四 {0}",
            week5t: "週五 {0}",
            week6t: "週六 {0}",
            month: "月",
            month0s: "1月",
            month1s: "2月",
            month2s: "3月",
            month3s: "4月",
            month4s: "5月",
            month5s: "6月",
            month6s: "7月",
            month7s: "8月",
            month8s: "9月",
            month9s: "10月",
            monthAs: "11月",
            monthBs: "12月",
            month0f: "一月",
            month1f: "二月",
            month2f: "三月",
            month3f: "四月",
            month4f: "五月",
            month5f: "六月",
            month6f: "七月",
            month7f: "八月",
            month8f: "九月",
            month9f: "十月",
            monthAf: "十一月",
            monthBf: "十二月",
            year: "年",
            am: "上午",
            pm: "下午",
            empty: "暫無",
            commaSymbol: "，",
            colonSymbol: ":",
            ellipsisSymbol: "...",
            semicolonSymbol: "; ",
            enumCommaSymbol: "、",
            periodSymbol: "。"
        };

        public template(templ: AliHub.Res.Templates): AliHub.Res.Templates {
            if (!templ) return null;
            templ.strings.reg(this.lang, this.strings);
            templ.strings.reg("zh-TW", this.strings);
            templ.strings.reg("zh-HK", this.strings);
            templ.strings.reg("zh-MO", this.strings);
            return templ;
        }
    }

    // Loads the language pack.
    (new Lp_zhHans).template(builtIn());
    (new Lp_zhHant).template(builtIn());
}
