# --------------------
# Git utilities - Alibaba CRM
# (c) Kingcean Tuan, 2015.
#
# File  git.ps1
# Description  Utilities of Git.
# Owner  Kingcean Tuan <kingcean@live.com>
# --------------------  */

Function SetVersion([int[]]$version)
{
}

Function Pull()
{
    git pull
}

Function Commit([string]$message)
{
}

Function Push()
{
}

# SIG # Begin signature block
# MIIFrwYJKoZIhvcNAQcCoIIFoDCCBZwCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUNfEjkHF0WgWxWQ+TDGFqi6tf
# gNygggM/MIIDOzCCAiegAwIBAgIQDS+bT70PDZ5CwkvBATsgpDAJBgUrDgMCHQUA
# MCUxIzAhBgNVBAMTGktpbmcgU2lnbmF0dXJlIGZvciBBbGliYWJhMB4XDTE1MDEz
# MDA4MzMyNFoXDTM5MTIzMTIzNTk1OVowJTEjMCEGA1UEAxMaS2luZyBTaWduYXR1
# cmUgZm9yIEFsaWJhYmEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCK
# D4QzS8PrpH4AlJZIAIa73F3NMs03/m3WLDpSavrqio7QumAC9kAmGeZRUBfn3ma5
# dfcKIeUPob5WBoEHfzO3Syi6bV7O17wjDsjJboeOFECi+9ZAcXgpqbVrH9RdrKJ3
# l/oxnfhx9OGBnhBx19BRpAnYmZk6VMb1SDTkdzqCLy/BEVCEG9WtuZJTie4DPRAa
# bsZJHn28FjlhmSHWZJDPrG34TClQLi4c0Zjemq8GfSTd2io1Pcee4CXTcp7dLrxn
# tkm83KZa8o5I2wCFgUII9Zl0IFYpLyk4XSgVdNa2Rtli+tCffvZlFqkspPiY7Ldn
# J52lHkfUB+G9rHcS0jBlAgMBAAGjbzBtMBMGA1UdJQQMMAoGCCsGAQUFBwMDMFYG
# A1UdAQRPME2AEJM+gAZfL8L7LTdmtOo5f3+hJzAlMSMwIQYDVQQDExpLaW5nIFNp
# Z25hdHVyZSBmb3IgQWxpYmFiYYIQDS+bT70PDZ5CwkvBATsgpDAJBgUrDgMCHQUA
# A4IBAQAzcawvuGar2si+7fJPWU1JTQZF8jhbviZWvYkRdFPthuU7mZ/Fux4pgPiU
# oi6aF5wgtjXZ+NzXG/QBNzGIYvXpL9vSQlUM2dL+2j+Dz80FyU/BjuXmdB0fNBqH
# op27TGezwdmGAyi0mIVp4WKxkje3c+KtulQxwvvm8YvAlZl/sLv7YacIf2ccHZvs
# nb4M4g/KU5cestkA5maJBTW/Pr7dtTXUDkb3k13yj4ljZWb3yDXBzgmibz3pP9x0
# Lh8N6LIDU5V1Q00mX+f1SYjpGU2GqkpuZdtj0eDBafzo6LIQMgjMk4tiafOAt3eb
# cbCGiuzktYRoTwf+cTwR5o1HPzFgMYIB2jCCAdYCAQEwOTAlMSMwIQYDVQQDExpL
# aW5nIFNpZ25hdHVyZSBmb3IgQWxpYmFiYQIQDS+bT70PDZ5CwkvBATsgpDAJBgUr
# DgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMx
# DAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkq
# hkiG9w0BCQQxFgQU6hVlD95I8qI8UoBCFdBbXppmcrQwDQYJKoZIhvcNAQEBBQAE
# ggEAbCkz38vnPZO3lXFq90OFrvH/3EvYHi3v0Mrt7cr1FCKr4YCtvL85GoMO6he7
# +3rEs0QNzWKbjr1q+C3Jr2tWk/gCfcgmnMEGcJP3p9i+4HWxnt399E07YE3P5Kl7
# qMAF2lfFTTY9roRULSfP5nZ6Fv9zwAy8e/PMuPZhiSk6DLousZlAjREal8K7lWSl
# E+r1qotRNYSr57kx5/I5TMk7QUNBIF0Rkkatey5XEQ2ndDcCN2jFgSgUMLR8Pxnm
# G2V0/xefNFj3iylupVspsGUqNSYqEzyybIqHplhk1PENxDu6XkzaQSm6BWiBTFwa
# GuHOzibUNpjqRPJgetet7k6FyQ==
# SIG # End signature block
